use_frameworks!

platform :ios, '15.0'

target 'flagshipHorizon_Example' do
  pod 'flagshipHorizon/OpenFeature', :path => '../'

  target 'flagshipHorizon_Tests' do
    inherit! :search_paths

    
  end
end
